version: 0.6.{build}
skip_tags: true
configuration: Release
platform: AnyCPU
clone_depth: 2
test: off
branches:
  only:
  - master
install:
- choco install gitlink -y
- choco install docfx -y
before_build:
- ps: .\SetVersion.ps1
- appveyor-retry dotnet restore -v Minimal
- ps: if(-not $env:APPVEYOR_PULL_REQUEST_NUMBER) { $env:is_not_pr = "true"; }
before_package:
- ps: if(-not $env:APPVEYOR_PULL_REQUEST_NUMBER) { GitLink .\ }
environment:
  COVERALLS_REPO_TOKEN:
    secure: 7WKQnyTUvZhaCOIVI2+CmP/1tV9nJNHgZ6VJFa3lhxD81O9sJGp65DA/uG4sRyG9
  jira_test_username:
    secure: gdcMwbkCpbe2jH691vkZqw==
  jira_test_password:
    secure: Ok03X5fvfNY2h61MHktUJw==
  sonar_token:
    secure: QIaJEHgudzCCUvtIOmDZEUVHzOUF9+d4J0ghEEbuJBj+QW3li6lK053A1kftp8CX
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
build_script:
- dotnet build src\Dapplo.Jira -c %CONFIGURATION% --no-dependencies
- dotnet build src\Dapplo.Jira.PowerShell -c %CONFIGURATION% --no-dependencies
- dotnet build src\Dapplo.Jira.Tests -c %CONFIGURATION% --no-dependencies
after_build:
- ps: .\CreateCoverage.ps1
- docfx doc\docfx.json
- 7z a -tzip %APPVEYOR_BUILD_FOLDER%\artifacts\site.zip -r %APPVEYOR_BUILD_FOLDER%\doc\_site\*.*
- dotnet pack src\Dapplo.Jira -c %CONFIGURATION% --no-build -o artifacts
#- dotnet pack Dapplo.Jira.PowerShell -c %CONFIGURATION% --no-build -o artifacts
#cache:
#- '%USERPROFILE%\.nuget\packages'
artifacts:
- path: artifacts\**\*.nupkg
- path: artifacts\**\site.zip
notifications:
- provider: Email
  to:
  - robin@dapplo.net
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
deploy:
- provider: NuGet
  skip_symbols: true
  api_key:
    secure: xkDQ385+smLqdzhESsXBJvnUjK4FZ4Djjrqi9tFR29dwESIvPYOrQAqgri5Nf/fA
  on:
    branch: master
    is_not_pr: true
    appveyor_repo_commit_message_extended: /\[release\]/