# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
  batch: true
  branches:
    include:
    - '*'
    exclude:
    - gh-pages

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'Windows-latest'

    variables:
      solution: '**/src/*.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'

    steps:
    - task: NuGetToolInstaller@1

    - task: UseDotNet@2
      displayName: 'Use .NET Core sdk 3.1'
      inputs:
        packageType: sdk
        version: 3.1.100

    - task: DotNetCoreCLI@2
      displayName: Test
      condition: ne(variables['Build.Reason'], 'PullRequest')
      inputs:
        command: test
        projects: '$(solution)'
        arguments: '--configuration Debug /p:Platform="$(buildPlatform)" /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura'
      env:
        jira_test_username: $(jira_test_username)
        jira_test_password: $(jira_test_password)

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: build
        projects: '$(solution)'
        arguments: '--configuration $(buildConfiguration) /p:Platform="$(buildPlatform)"'

    - task: CopyFiles@2
      displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          **\bin\$(buildConfiguration)\*.nupkg
          **\coverage.*
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        flattenFolders: true

    - task: PublishCodeCoverageResults@1
      condition: ne(variables['Build.Reason'], 'PullRequest')
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: 'src/**/coverage.cobertura.xml'
        failIfCoverageEmpty: true

    - powershell: |
        choco install docfx -y
        docfx doc/docfx.json
        if ($lastexitcode -ne 0){
          throw ("Error generating docfx document")
        }
      displayName: "docfx build"

    - task: CopyFiles@2
      displayName: 'Copy documentation files to: $(Build.ArtifactStagingDirectory)'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)/doc/_site'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/site'

    - task: PublishPipelineArtifact@1
      displayName: 'Publish Artifacts'
      condition: ne(variables['Build.Reason'], 'PullRequest')
      inputs:
        artifactName: 'drop'
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'

- stage: Deploy
  jobs:
  - deployment: DeployNuGet
    condition: ne(variables['Build.Reason'], 'PullRequest')
    pool:
      vmImage: 'Windows-latest'

    environment: 'NuGet'
    strategy:
      # default deployment strategy
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              artifact: 'drop'

          - task: NuGetToolInstaller@0
            displayName: 'Use NuGet 5.4.0'
            inputs:
              versionSpec: 5.4.0
              checkLatest: true

          - task: NuGetCommand@2
            displayName: 'NuGet push'
            inputs:
              command: push
              packagesToPush: '$(Pipeline.Workspace)/drop/a/*.nupkg;!$(Pipeline.Workspace)/drop/a/*.symbols.nupkg'
              nuGetFeedType: external
              publishFeedCredentials: 'Dapplo NuGet push'
